zuul:
  host:
    connect-timeout-millis: 400000
    socket-timeout-millis: 400000
  # This config remove the X-Forwarded-Prefix
  # addProxyHeaders: false
  routes:
    any:
      path: /**
      # This config forward all headers
      sensitiveHeaders:
      url: ${URL:https://localhost:8080}


security:
  require-ssl: true

server:
  port: ${PORT:8443}
  ssl:
    enabled: true
    key-store: ${KEY_STORE_PATH:keystore.jks}
    key-store-password: ${KEY_STORE_PASS:123456}
    keyStoreType: ${KEY_STORE_TYPE:JKS}